const path = require("path");
const webpack = require("webpack");

module.exports = {
  entry: path.resolve(__dirname, "src/js/index.js"),
  output: {
    path: path.resolve(__dirname, "dist"),
    filename: "material.min.js",
    library: "Material",
    libraryTarget: "umd",
  },
  module: {
    rules: [
      {
        test: /\.(js)$/,
        exclude: /node_modules/,
        use: "babel-loader",
      },
    ],
  },
  mode: "production",
  plugins: [
    new webpack.BannerPlugin(`
         Tronic247 Material design - v3.0
         https://material.tronic247.com
        
         Copyright (C) 2021 "Tronic247" Posandu Mapa
         licensed under the MIT license.
         https://github.com/Tronic247/material/blob/Main/LICENSE
         `),
  ],
  optimization: {
    minimizer: [
      (compiler) => {
        const TerserPlugin = require("terser-webpack-plugin");
        new TerserPlugin({
          terserOptions: {
            caseSensitive: true,
            collapseBooleanAttributes: true,
            collapseInlineTagWhitespace: false,
            collapseWhitespace: true,
            conservativeCollapse: false,
            continueOnParseError: true,
            decodeEntities: true,
            html5: true,
            includeAutoGeneratedTags: false,
            keepClosingSlash: false,
            maxLineLength: 0,
            minifyCSS: true,
            minifyJS: true,
            preserveLineBreaks: false,
            preventAttributesEscaping: false,
            processConditionalComments: true,
            processScripts: ["text/html"],
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            removeEmptyElements: true,
            removeOptionalTags: true,
            removeRedundantAttributes: true,
            removeScriptTypeAttributes: true,
            removeStyleLinkTypeAttributes: true,
            removeTagWhitespace: true,
            sortAttributes: true,
            sortClassName: true,
            trimCustomFragments: true,
            useShortDoctype: true,
          },
        }).apply(compiler);
      },
    ],
  },
};
