on:
  push:
    branches:
      - v3-dev
      
jobs:
  build_css:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0

      - name: Checkout source Git branch
        uses: actions/checkout@v2

      - name: Compile SCSS
        uses: gha-utilities/sass-build@v0.4.3
        with:
          source: src/scss/index.scss
          destination: dist/css/material.min.css

      - name: Auto committing build files
        uses: stefanzweifel/git-auto-commit-action@v3.0.0
        with:
          commit_message: "Compile Files"
          branch: v3-dev
     
