on:
  push:
    branches:
      - main
      
jobs:
  build_css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
            ref: main
            fetch-depth: 10
            submodules: false

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.4.3
        with:
          source: src/src.scss
          destination: dist/css/material.min.css

      - name: Add and Commit changes
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          rm -r dist/css
          git add .
          git commit -m 'Updates compiled CSS files'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
