on: push
name: 'Build'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Add comments
        run: node _comment.js
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Build Files
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
