on: push
name: 'Build'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
            node-version: '14'
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Add comments
        run: node _comment.js
      - name: Purge Cache
        run: node _purge.js
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Build Files
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
