on:
  push:
    branches:
      - main
      
jobs:
  build_css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v2

      - name: Compile SCSS
        uses: gha-utilities/sass-build@v0.4.3
        with:
          source: src/scss/index.scss
          destination: dist/css/material.min.css
          
      - name: Compile JS
        uses: jossydevers/transpiler-js@v1.0.0
        with:
          typename: min
          directory: src/js
          output: dist/

      - name: Auto committing build files
        uses: stefanzweifel/git-auto-commit-action@v3.0.0
        with:
          commit_message: "Build for JS and SCSS files"
          branch: ${{ github.ref }}
